---
- hosts: LB
  remote_user: vagrant
  sudo: yes
  vars:
    haproxy_app_name: myapp
    haproxy_mode: http
    haproxy_enable_stats: enable 
    haproxy_algorithm: roundrobin
    haproxy_backend_servers:
    - {name: server1, ip: web01, port: 80, paramstring: cookie A check}
    - {name: server2, ip: web02, port: 80, paramstring: cookie A check}
    haproxy_stats_users:
    - {username: admin, password: admin}
  
  tasks:

    - name: install haproxy
      apt: name=haproxy state=present
   
    - name: Update HAProxy config
      template: src=haproxy.conf 
                dest=/etc/haproxy/haproxy.cfg 
                backup=yes
    
    - name: Enable init script
      lineinfile: dest=/etc/default/haproxy regexp="^ENABLED=0" line="ENABLED=1"

    - name: restart machine
      command: reboot
      async: 0
      poll: 0
      ignore_errors: true
